name: BSD CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  freebsd:
    name: FreeBSD 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Build and test
        uses: vmactions/freebsd-vm@v1.5.4
        with:
          release: '15'
          usesh: true
          cache-after-prepare: true
          prepare: |
            pkg install -y meson ninja
          run: |
            meson setup build
            meson compile -C build
            meson test -C build --print-errorlogs

  netbsd:
    name: NetBSD 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Build and test
        uses: vmactions/netbsd-vm@v1.4.6
        with:
          release: '11'
          cache-after-prepare: true
          prepare: |
            /usr/sbin/pkg_add -u meson ninja
          run: |
            meson setup build
            meson compile -C build
            meson test -C build --print-errorlogs

  openbsd:
    name: OpenBSD 7.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Build and test
        uses: vmactions/openbsd-vm@v1.4.6
        with:
          release: '7.9'
          cache-after-prepare: true
          prepare: |
            pkg_add meson ninja
          run: |
            meson setup build
            meson compile -C build
            meson test -C build --print-errorlogs
